---
- name: Export a directory using NFS
  hosts: servera.lab.example.com
  vars:
    shared_dir: /nfsshare

  tasks:

    - name: the directory exists
      file:
        path: "{{ shared_dir }}"
        owner: student
        state: directory

    - name: the directory is exported
      template:
        src: templates/share.exports.j2
        dest: /etc/exports.d/share.exports
      notify: reload exports

    - name: the nfs-server service is started and enabled
      service:
        name: nfs-server
        state: started
        enabled: yes

    - name: the nfs firewall service is opened
      firewalld:
        service: nfs
        state: enabled
        immediate: yes
        permanent: yes

  handlers:
    - name: reload exports
      service:
        name: nfs-server
        state: reloaded
